### ISSUE TITLE
Update CTL with better information about conformance classes

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sfs12#1]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by dstenger** [comment]
No actual tests are implemented and just a file upload is existing.

Thus, basic conformance classes cannot be configured.
