### ISSUE TITLE
Is SFS 1.2 test suite download link wrong?

### ISSUE THREAD

**Issue by jiayuasu** [opengeospatial/ets-sfs12#2]
As stated in this SFS 1.2 README,
>Test suite software is available (ZIP archive) for each of the above alternatives as a set of SQL scripts and as C source code. Implementers may select either form of test suite for adaptation and testing.

The given link is `http://portal.opengeospatial.org/files/?artifact_id=16317`. The downloaded file is titled as `SFSQL_1.1_Compliance_Test_Suite`.

Is the test suite for SFS 1.1 not for 1.2?

Can you please let me know where I can find the test suite for SFS 1.2 to perform a conformance test? I have searched everywhere on the internet.

**Comment by dstenger** [comment]
The code for SFS 1.2 test suite should be available in this GitHub repository. However, it contains no actual tests.

README of SFS 1.2 states:
```The specification provides the rules to support storage, retrieval, query and update of feature collections via the SQL Call-Level Interface (SQL/CLI). Three conformance classes are described in the testing guidance document (see OGC 98-046r2) and in Annex A Table A1 of OGC 06-104r4.```
```Section A.4.1 of 06-104r4 provides more details about the conformance classes choices (gt,b,2d,N,tn, etc.). The test for these 3 conformance classes are the same as for SFS 1.1 OGC 99-049.```

Thus, the tests for SFS 1.2 seem to be the same as implemented for SFS 1.1.

@bermud Do you have additional informations regarding this question?

**Comment by pramsey** [comment]
Having looked at the ZIP file that is linked, the 1.2 "tests" are just the 1.1 "tests". So they use 1.1 function signatures instead of 1.2 ones (no "ST_" prefix) and incredibly still contain all the straight-up mistakes from the 1.1 suite.

**Comment by bermud** [comment]
@pramsey, thank you for reporting the issue and pointing it to me at FOSS4GNA. I suggest we start with your suggestions on 1.1 and then we will tackle 1.2. Thank you very much!!!

**Comment by dstenger** [comment]
Question should be answered.

Tests are fixed in https://github.com/opengeospatial/ets-sfs12/issues/3.
