### ISSUE TITLE
SQL Tests are Wrong

### ISSUE THREAD

**Issue by pramsey** [opengeospatial/ets-sfs12#3]
When I found this repo, I was hoping to be able to submit a PR to actually update the suite SQL files, because they are full of errors. Whoever wrote them (20 years ago!) never actually ran them on a live database, as they use function signatures that aren't in the spec, and occasionally reference tables that don't hold the data they are searching for. Are the SQL files going to be added to GitHub? (I know, this is really quite pointless, nobody "cares", but my OGC conformance scripts includes lines [like these](https://github.com/postgis/postgis/blob/svn-2.5/extras/ogc_test_suite/2_queries.sql#L218-L221), and it tasks me.

**Comment by dstenger** [comment]
Hi Paul,
you are welcome to submit a pull request to this repository.
We will take care of the rest then.
Also, we can support you if you need any help.

**Comment by pramsey** [comment]
Where would the SQL files go, in your directory structure? I see lots of fancy maven stuff.

**Comment by dstenger** [comment]
Actually, this repository does not contain the actual test suite but provides an interface to upload test results.

The actual test suite can be found here: http://portal.opengeospatial.org/files/?artifact_id=16317
which is linked here http://opengeospatial.github.io/ets-sfs12/.

Thus, this is not the correct repository to submit a pull request regarding the actual tests.

@bermud How can pramsey submit the updated SQL scripts to actual test suite? Can you help us here?

**Comment by bermud** [comment]
I think the test is similar to 1.1. I have added the 1.1 test here: https://github.com/opengeospatial/ets-sfs11/tree/master/src/site/resources/test-sql-commands. I will investigate further in the coming weeks the status of this test and the relation with 1.1. Please @pramsey suggest any changes in the 1.1 repo. thank you!

**Comment by dstenger** [comment]
@pramsey 
You are very much welcome to create a pull request with correct tests in directory `src/site/resources/test-sql-commands`.
We will take care of the rest then (e.g. updating link in test suite documentation).

**Comment by ghobona** [comment]
@pramsey 

Please create the Pull Request with the location suggested by the Issue Comment https://github.com/opengeospatial/ets-sfs12/issues/3#issuecomment-499086619

**Comment by ghobona** [comment]
Closing the Issue due to no reply.
